---
services:
  backend:
    build: ./backend
    ports:
      - "5055:5055"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    networks:
      - my_network
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017/mongoLDO


  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5003:3000"
    volumes:
      - type: bind
        source: ./frontend/src/
        target: /app/src/
    environment:
      - REACT_APP_LISTEN_ADDRESS=${REACT_APP_LISTEN_ADDRESS}
    networks:
      - my_network

  mongo:
    image: mongo:latest
    container_name: mongoLDO
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - my_network

volumes:
  mongo-data:

networks:
  my_network:
    driver: bridge