// Character Sheet Components — Props-based (refatorados UI-006)
export { default as CharacterHeader } from './CharacterHeader';
export { default as CombatVitalSection } from './CombatVitalSection';
export { default as EquipamentosSection } from './EquipamentosSection';
export { default as HabilidadesSection } from './HabilidadesSection';
export { default as ProficienciasSection } from './ProficienciasSection';
export { default as RegaliasSection } from './RegaliasSection';
export { default as ConditionsPanel } from './ConditionsPanel';
export { default as CapacidadeCargaPanel } from './CapacidadeCargaPanel';
export { default as DiceResultDisplay } from './DiceResultDisplay';
export { default as DiceHistorySidebar } from './DiceHistorySidebar';
export { default as DescansoPanel } from './DescansoPanel';
export { default as EditableField } from './EditableField';
